image:
  file: .gitpod.Dockerfile
ports:
  - port: 8787
    onOpen: open-browser
  - port: 3000-8786
    onOpen: ignore
  - port: 8786-15000
    onOpen: ignore
tasks:
  - name: setup
    env:
      R_LIBS_USER: /home/gitpod/libs
      R_PROFILE: /workspace/tidytuesdays-distill/.Rprofile
    command: /usr/lib/rstudio-server/bin/rstudio-server start